### **Student Information**
Name:

Student ID:

GitHub ID:

Kaggle name:

Kaggle private scoreboard snapshot: 

![pic_ranking.png](./pics/pic_ranking.png)

---

# **Instructions**

For this lab we have divided the assignments into **three phases/parts**. The `first two phases` refer to the `exercises inside the Master notebooks` of the [DM2025-Lab2-Exercise Repo](https://github.com/difersalest/DM2025-Lab2-Exercise.git). The `third phase` refers to an `internal Kaggle competition` that we are gonna run among all the Data Mining students. Together they add up to `100 points` of your grade. There are also some `bonus points` to be gained if you complete `extra exercises` in the lab **(bonus 15 pts)** and in the `Kaggle Competition report` **(bonus 5 pts)**.

**Environment recommendations to solve lab 2:**
- **Phase 1 exercises:** Need GPU for training the models explained in that part, if you don't have a GPU in your laptop it is recommended to run in Colab or Kaggle for a faster experience, although with CPU they can still be solved but with a slower execution.
- **Phase 2 exercises:** We use Gemini's API so everything can be run with only CPU without a problem.
- **Phase 3 exercises:** For the competition you will probably need GPU to train your models, so it is recommended to use Colab or Kaggle if you don't have a laptop with a dedicated GPU.
- **Optional Ollama Notebook (not graded):** You need GPU, at least 4GB of VRAM with 16 GB of RAM to run the local open-source LLM models. 

## **Phase 1 (30 pts):**

1. __Main Exercises (25 pts):__ Do the **take home exercises** from Sections: `1. Data Preparation` to `9. High-dimension Visualization: t-SNE and UMAP`, in the [DM2025-Lab2-Master-Phase_1 Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_1.ipynb). Total: `8 exercises`. Commit your code and submit the repository link to NTU Cool **`BEFORE the deadline (Nov. 3th, 11:59 pm, Monday)`**

2. **Code Comments (5 pts):** **Tidy up the code in your notebook**. 

## **Phase 2 (30 pts):**

1. **Main Exercises (25 pts):** Do the remaining **take home exercises** from Section: `2. Large Language Models (LLMs)` in the [DM2025-Lab2-Master-Phase_2_Main Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_2_Main.ipynb). Total: `5 exercises required from sections 2.1, 2.2, 2.4 and 2.6`. Commit your code and submit the repository link to NTU Cool **`BEFORE the deadline (Nov. 24th, 11:59 pm, Monday)`**

2. **Code Comments (5 pts):** **Tidy up the code in your notebook**. 

3. **`Bonus (15 pts):`** Complete the bonus exercises in the [DM2025-Lab2-Master-Phase_2_Bonus Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_2_Bonus.ipynb) and [DM2025-Lab2-Master-Phase_2_Main Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_2_Main.ipynb) `where 2 exercises are counted as bonus from sections 2.3 and 2.5 in the main notebook`. Total: `7 exercises`. Commit your code and submit the repository link to NTU Cool **`BEFORE the deadline (Nov. 24th, 11:59 pm, Monday)`**

## **Phase 3 (40 pts):**

1. **Kaggle Competition Participation (30 pts):** Participate in the in-class **Kaggle Competition** regarding Emotion Recognition on Twitter by clicking in this link: **[Data Mining Class Kaggle Competition](https://www.kaggle.com/t/3a2df4c6d6b4417e8bf718ed648d7554)**. The scoring will be given according to your place in the Private Leaderboard ranking: 
    - **Bottom 40%**: Get 20 pts of the 30 pts in this competition participation part.

    - **Top 41% - 100%**: Get (0.6N + 1 - x) / (0.6N) * 10 + 20 points, where N is the total number of participants, and x is your rank. (ie. If there are 100 participants and you rank 3rd your score will be (0.6 * 100 + 1 - 3) / (0.6 * 100) * 10 + 20 = 29.67% out of 30%.)   
    Submit your last submission **`BEFORE the deadline (Nov. 24th, 11:59 pm, Monday)`**. Make sure to take a screenshot of your position at the end of the competition and store it as `pic_ranking.png` under the `pics` folder of this repository and rerun the cell **Student Information**.

2. **Competition Report (10 pts)** A report section to be filled in inside this notebook in Markdown Format, we already provided you with the template below. You need to describe your work developing the model for the competition. The report should include a section describing briefly the following elements: 
* Your preprocessing steps.
* The feature engineering steps.
* Explanation of your model.

* **`Bonus (5 pts):`**
    * You will have to describe more detail in the previous steps.
    * Mention different things you tried.
    * Mention insights you gained. 

[Markdown Guide - Basic Syntax](https://www.markdownguide.org/basic-syntax/)

**`Things to note for Phase 3:`**

* **The code used for the competition should be in this Jupyter Notebook File** `DM2025-Lab2-Homework.ipynb`.

* **Push the code used for the competition to your repository**.

* **The code should have a clear separation for the same sections of the report, preprocessing, feature engineering and model explanation. Briefly comment your code for easier understanding, we provide a template at the end of this notebook.**

* Showing the kaggle screenshot of the ranking plus the code in this notebook will ensure the validity of your participation and the report to obtain the corresponding points.

After the competition ends you will have two days more to submit the `DM2025-Lab2-Homework.ipynb` with your report in markdown format and your code. Do everything **`BEFORE the deadline (Nov. 26th, 11:59 pm, Wednesday) to obtain 100% of the available points.`**

Upload your files to your repository then submit the link to it on the corresponding NTU Cool assignment.

## **Deadlines:**

![lab2_deadlines](./pics/lab2_deadlines.png)

---

Next you will find the template report with some simple markdown syntax explanations, use it to structure your content.

You can delete the syntax suggestions after you use them.

---

***

# **Project Report**

**Syntax:** `#` creates the largest heading (H1).

---
**Syntax:** `---` creates a horizontal rule (a separator line).

## 1. Model Development (10 pts Required)

**Syntax:** `##` creates a secondary heading (H2).

**Describe briefly each section, you can add graphs/charts to support your explanations.**

### 1.1 Preprocessing Steps

**Syntax:** `###` creates a tertiary heading (H3).

[Content for Preprocessing]

**Example Syntax for Content:**
*   **Bold text:** `**text**`
*   *Italic text*: `*text*`
*   Bullet point list:
    * Item 1
    * Item 2

Markdown Syntax to Add Image: `![Description of the Image](./your_local_folder/name_of_the_image.png)`

![Example Markdown Syntax to Add Image](./pics/example_md_img.png)

### 1.2 Feature Engineering Steps

[Content for Feature Engineering]

### 1.3 Explanation of Your Model

[Content for Model Explanation]

---

## 2. Bonus Section (5 pts Optional)

**Add more detail in previous sections**

### 2.1 Mention Different Things You Tried

[Content for Experiments]

### 2.2 Mention Insights You Gained

[Content for Insights]

---

**`From here on starts the code section for the competition.`**

---

# **Competition Code**

## 1. Preprocessing Steps

In [1]:
!pip install transformers[torch] datasets scikit-learn pandas protobuf tiktoken sentencepiece emoji --quiet
import os, json, re, random, string, math, html, emoji, glob
os.environ["TOKENIZERS_PARALLELISM"] = "true"
from typing import Optional, List
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score
from sklearn.utils.class_weight import compute_class_weight
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from scipy.special import softmax
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import AdamW
torch.set_num_threads(4)
from datasets import Dataset
from transformers import AutoTokenizer, AutoConfig, AutoModelForSequenceClassification, TrainingArguments, Trainer, DataCollatorWithPadding, set_seed, EarlyStoppingCallback, default_data_collator 

In [2]:
SEED = 42
set_seed(SEED)
random.seed(SEED)
np.random.seed(SEED)

BASE_DIR = "kaggle"
paths = {
    "id": os.path.join(BASE_DIR, "data_identification.csv"),
    "emo": os.path.join(BASE_DIR, "emotion.csv"),
    "sub": os.path.join(BASE_DIR, "samplesubmission.csv"),
    "posts": os.path.join(BASE_DIR, "final_posts.json"),
}

has_cuda = torch.cuda.is_available()
has_rocm = getattr(torch.version, "hip", None) is not None
use_fp16 = bool(has_cuda and not has_rocm)
use_bf16 = not has_rocm and has_cuda and torch.cuda.is_bf16_supported()
print("CUDA:", has_cuda, "| ROCm:", has_rocm, "| use_fp16:", use_fp16, "| use_bf16:", use_bf16)


CUDA: True | ROCm: False | use_fp16: True | use_bf16: True


In [3]:
id_df  = pd.read_csv(paths["id"])  
emo_df = pd.read_csv(paths["emo"])    
sub_df = pd.read_csv(paths["sub"])     

with open(paths["posts"], "r", encoding="utf-8") as f:
    posts_json = json.load(f)

def extract_posts(records):
    ids, texts, hashtags = [], [], []
    for r in records:
        root = r.get("root", r)
        try:
            post = root["_source"]["post"]
            pid = post.get("post_id") or post.get("id")
            txt = post.get("text")
            tag = post.get("hashtags")
            if pid is not None and txt is not None:
                ids.append(pid)
                texts.append(txt)
                hashtags.append(tag)
        except Exception:
            continue
    return pd.DataFrame({"id": ids, "text": texts, "hashtags": hashtags})

posts_df = extract_posts(posts_json)
df = id_df.merge(posts_df, on="id", how="left").merge(emo_df, on="id", how="left")

## 2. Feature Engineering Steps

In [4]:
MULTI_WS    = re.compile(r"\s+")
LEAD_QUOTE  = re.compile(r"^\s*>+\s*")
NAME_PLACE = re.compile(r"\[NAME\]", re.IGNORECASE)
URL_PATTERN   = re.compile(r"http\S+|www\.\S+")
USER_PATTERN  = re.compile(r"@\w+")
EDIT_PATTERN = re.compile(r"(edit:|tl;dr)", re.IGNORECASE)

def attach_missing_list_hashtags(text: str, hashtags) -> str:
    words = set(w.lower() for w in re.findall(r"\b\w+\b", text))
    extra = []
    for h in hashtags:
        if not h:
            continue
        h_clean = str(h).strip("#").strip()
        if not h_clean:
            continue
        if h_clean.lower() not in words:
            extra.append(h_clean)
    if extra:
        text = text + " " + " ".join(extra)
    return text

    

def normalize_text(text: str, hashtags: Optional[str] = None) -> str:
    text = html.unescape(text)
    text = text.replace("\r", " ").replace("\n", " ").replace("\t", " ")

    text = emoji.demojize(text, delimiters=(" ", " "))
    
    # normalize user mentions, urls, name placeholders
    text = USER_PATTERN.sub(" <USER> ", text)
    text = URL_PATTERN.sub(" <URL> ", text)
    text = NAME_PLACE.sub(" <NAME> ", text)

    # remove leading > quotes
    text = LEAD_QUOTE.sub("", text)

    m = EDIT_PATTERN.search(text)
    if m:
        text = text[:m.start()]
        
    if isinstance(hashtags, list) and len(hashtags) > 0:
        tag_tokens = " ".join(f"#{h}" for h in hashtags if isinstance(h, str))
        text = f"{text} {tag_tokens}"

    text = emoji.demojize(text, language="en")
    # demojize drop colons
    text = text.replace(":", " ")


    # cleanup whitespace
    text = MULTI_WS.sub(" ", text).strip()
    return text

train_df = df[df["split"]=="train"].dropna(subset=["emotion"]).reset_index(drop=True)
test_df  = df[df["split"]=="test"].reset_index(drop=True)

train_df["text"] = train_df.apply(lambda r: normalize_text(r["text"], r["hashtags"]), axis=1)
test_df["text"] = test_df.apply(lambda r: normalize_text(r["text"], r["hashtags"]), axis=1)

labels = sorted(train_df["emotion"].unique().tolist())
label2id = {l:i for i,l in enumerate(labels)}
id2label = {i:l for l,i in label2id.items()}

y = train_df["emotion"].map(label2id).values.astype(int)
print("Train:", train_df.shape, "| Test:", test_df.shape, "| Classes:", labels)


Train: (47890, 5) | Test: (16281, 5) | Classes: ['anger', 'disgust', 'fear', 'joy', 'sadness', 'surprise']


In [5]:
# helpers
def make_ds(texts, labels=None):
    d = {"text": texts}
    if labels is not None:
        d["label"] = labels
    return Dataset.from_dict(d)

def tokenize_fn(examples, tokenizer, max_len=256):
    return tokenizer(examples["text"], truncation=True, max_length=max_len, padding="max_length",)

def compute_f1(eval_pred):
    logits = eval_pred.predictions
    labels = eval_pred.label_ids

    # logits = logits[0]
    logits = np.asarray(logits)
    preds = logits.argmax(axis=-1)

    macro = f1_score(labels, preds, average="macro")
    micro = f1_score(labels, preds, average="micro")
    return {"f1_macro": macro, "f1_micro": micro}

def augment_text(text: str) -> str:
    words = text.split()
    if len(words) <= 4:
        return text
    keep = []
    for w in words:
        # drop 10% of tokens at random
        if np.random.rand() < 0.1:
            continue
        keep.append(w)
    if not keep:
        keep = words
    return " ".join(keep)
    
def get_layer(name: str, num_hidden_layers: int) -> int:
    if "embeddings" in name:
        return 0
    for i in range(num_hidden_layers):
        if f"encoder.layer.{i}." in name:
            return i + 1
    return num_hidden_layers + 1

def reinit_layers(model, num_layers=3):
    if hasattr(model, "deberta"):
        encoder = model.deberta.encoder
    elif hasattr(model, "roberta"):
        encoder = model.roberta.encoder
    elif hasattr(model, "bert"):
        encoder = model.bert.encoder
    else:
        print("Could not identify encoder for re-initialization.")
        return

    print(f"Re-initializing the last {num_layers} layers...")
    for layer in encoder.layer[-num_layers:]:
        for module in layer.modules():
            if isinstance(module, nn.Linear):
                module.weight.data.normal_(mean=0.0, std=model.config.initializer_range)
                if module.bias is not None:
                    module.bias.data.zero_()
            elif isinstance(module, nn.LayerNorm):
                module.bias.data.zero_()
                module.weight.data.fill_(1.0)

## 3. Model Implementation Steps

In [20]:
class FocalLoss(nn.Module):
    def __init__(self, gamma=2.0, weight=None, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.gamma = gamma
        self.weight = weight
        self.reduction = reduction

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, weight=self.weight, reduction='none')
        pt = torch.exp(-ce_loss)
        focal_loss = ((1 - pt) ** self.gamma) * ce_loss
        if self.reduction == 'mean':
            return focal_loss.mean()
        return focal_loss.sum()

class WeightedTrainer(Trainer):
    def __init__(self,class_weight=None, rdrop_alpha: float = 0.0, layerwise_lr_decay: float = 1.0, 
                    label_smoothing_factor: float = 0.05, gamma: float = 0.0, **kwargs,):
        super().__init__(**kwargs)
        class_weight = torch.tensor(class_weight, dtype=torch.float)
        self.class_weight = class_weight
        self.gamma = float(gamma)
        self.rdrop_alpha = float(rdrop_alpha)
        self.layerwise_lr_decay = float(layerwise_lr_decay)

    # llrd
    def create_optimizer(self):
        if self.optimizer is not None:
            return self.optimizer

        lr = self.args.learning_rate
        wd = self.args.weight_decay
        layer_decay = self.layerwise_lr_decay

        if layer_decay == 1.0:
            return super().create_optimizer()

        model = self.model
        num_layers = getattr(model.config, "num_hidden_layers", 12)

        layer_parameters = {}
        for name, param in model.named_parameters():
            if not param.requires_grad:
                continue
            layer_id = get_layer(name, num_layers)
            layer_parameters.setdefault(layer_id, []).append((name, param))

        optimizer_grouped_parameters = []
        max_layer_id = max(layer_parameters.keys())
        no_decay = ["bias", "LayerNorm.weight"]

        for layer_id in sorted(layer_parameters.keys()):
            scale = layer_decay ** (max_layer_id - layer_id)
            layer_lr = lr * scale
            layer_params = layer_parameters[layer_id]

            decay_params = [
                p for n, p in layer_params
                if not any(nd in n for nd in no_decay)
            ]
            nodecay_params = [
                p for n, p in layer_params
                if any(nd in n for nd in no_decay)
            ]

            if decay_params:
                optimizer_grouped_parameters.append({"params": decay_params, "lr": layer_lr, "weight_decay": wd})
            if nodecay_params:
                optimizer_grouped_parameters.append(
                    {"params": nodecay_params, "lr": layer_lr, "weight_decay": 0.0}
                )

        self.optimizer = AdamW(
            optimizer_grouped_parameters,
            lr=lr,
            betas=(self.args.adam_beta1, self.args.adam_beta2),
            eps=self.args.adam_epsilon,
        )
        return self.optimizer

    def ce_loss(self, logits, labels):
        if labels.ndim > 1:
            labels = labels.view(-1)
        labels = labels.long()

        if logits.ndim > 2:
            logits = logits.view(logits.size(0), -1)

        assert logits.size(0) == labels.size(0), (f"logits batch {logits.size()} vs labels {labels.size()}")

        weight = self.class_weight.to(logits.device)
        gamma = self.gamma
        if gamma > 0.0:
            focal_loss_fn = FocalLoss(gamma=gamma, weight=weight)
            return focal_loss_fn(logits, labels)
        else:
            return F.cross_entropy(logits, labels, weight=weight, label_smoothing=0.05)

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        labels = inputs.pop("labels")
        outputs1 = model(**inputs)
        logits1 = outputs1.logits

        if self.rdrop_alpha > 0.0:
            outputs2 = model(**inputs)
            logits2 = outputs2.logits

            loss1 = self.ce_loss(logits1, labels)
            loss2 = self.ce_loss(logits2, labels)
            loss_ce = 0.5 * (loss1 + loss2)

            # symmetric kl on softmax
            p_log = F.log_softmax(logits1, dim=-1)
            q_log = F.log_softmax(logits2, dim=-1)
            p = p_log.exp()
            q = q_log.exp()
            kl_pq = F.kl_div(p_log, q, reduction="batchmean")
            kl_qp = F.kl_div(q_log, p, reduction="batchmean")
            loss_kl = 0.5 * (kl_pq + kl_qp)

            loss = loss_ce + self.rdrop_alpha * loss_kl

            if return_outputs:
                avg_logits = 0.5 * (logits1 + logits2)
                outputs1.logits = avg_logits
                return loss, outputs1
            return loss
        else:
            loss = self.ce_loss(logits1, labels)
            if return_outputs:
                return loss, outputs1
            return loss

In [21]:
class MultiHeadClassifier(nn.Module):
    def __init__(self, input_dim, num_labels, n_heads=4, p=0.2):
        super().__init__()
        self.n_heads = n_heads
        self.dropouts = nn.ModuleList([nn.Dropout(p) for _ in range(n_heads)])
        self.classifiers = nn.ModuleList(
            [nn.Linear(input_dim, num_labels) for _ in range(n_heads)]
        )

    def forward(self, x):
        if x.dim() == 3:
            x = x[:, 0, :]  # [B, H]

        logits = 0
        for i in range(self.n_heads):
            logits = logits + self.classifiers[i](self.dropouts[i](x))
        return logits / self.n_heads  # [B, num_labels]


In [ ]:
def train_folds(model_name, n_splits=5, lr=2e-5, epochs=3, bsz=16, max_len=192, wd=0.01, seed=SEED, n_heads=4, head_dropout=None):

    tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

    new_tokens = ["<USER>", "<URL>", "<NAME>"]
    new_tokens = [t for t in new_tokens if t not in tokenizer.get_vocab()]
    
    if new_tokens:
        print(f"Adding {len(new_tokens)} special tokens: {new_tokens}")
        tokenizer.add_tokens(new_tokens)
    
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)

    oof_preds = np.zeros((len(train_df), len(labels)), dtype=np.float32)
    test_logits_accum = np.zeros((len(test_df), len(labels)), dtype=np.float32)

    for fold, (tr_idx, va_idx) in enumerate(skf.split(train_df, y), 1):
        output_dir = f"./out_{os.path.basename(model_name)}_f{fold}"
        print(f"\n[{model_name}] Fold {fold}/{n_splits}")
        tr_df = train_df.iloc[tr_idx].copy()

        tr_texts = tr_df["text"].tolist()
        tr_labels = tr_df["emotion"].map(label2id).tolist()

        va_texts = train_df.loc[va_idx, "text"].tolist()
        va_labels = train_df.loc[va_idx, "emotion"].map(label2id).tolist()

        ds_tr = make_ds(tr_texts, tr_labels).map(lambda ex: tokenize_fn(ex, tokenizer, max_len), batched=True)
        ds_va = make_ds(va_texts, va_labels).map(lambda ex: tokenize_fn(ex, tokenizer, max_len), batched=True)

        tr_y = y[tr_idx]
        classes = np.unique(tr_y)
        raw_class_weight = compute_class_weight("balanced", classes=classes, y=tr_y)
        gamma = 0.5
        class_weight = np.power(raw_class_weight, gamma)

        ds_te = make_ds(test_df["text"].tolist()).map(lambda ex: tokenize_fn(ex, tokenizer, max_len), batched=True)

        cols = ["input_ids","attention_mask","label"]
        ds_tr.set_format(type="torch", columns=[c for c in cols if c in ds_tr.column_names])
        ds_va.set_format(type="torch", columns=[c for c in cols if c in ds_va.column_names])
        ds_te.set_format(type="torch", columns=[c for c in ["input_ids","attention_mask"] if c in ds_te.column_names])

        config = AutoConfig.from_pretrained(
            model_name,
            num_labels=len(labels),
            label2id=label2id,
            id2label=id2label,
            hidden_dropout_prob=0.2,
            attention_probs_dropout_prob=0.2,
        )

        config.problem_type = "single_label_classification"
        model = AutoModelForSequenceClassification.from_pretrained(
            model_name,
            config=config,
            ignore_mismatched_sizes=True,
        )
        
        model.resize_token_embeddings(len(tokenizer))
        # reinit_layers(model, num_layers=3)
        hidden_size = config.hidden_size
        
        if head_dropout is None:
            head_dropout = config.hidden_dropout_prob
            
        model.classifier = MultiHeadClassifier(
            input_dim=hidden_size,
            num_labels=len(labels),
            n_heads=n_heads,
            p=head_dropout,
        )

        args = TrainingArguments(
            output_dir=f"./out_{os.path.basename(model_name)}_f{fold}",
            learning_rate=lr,
            per_device_train_batch_size=bsz,
            per_device_eval_batch_size=bsz*2,
            num_train_epochs=epochs,
            weight_decay=wd,
            eval_strategy="epoch",
            save_strategy="epoch",
            load_best_model_at_end=True,
            metric_for_best_model="f1_macro", 
            save_total_limit=1,
            logging_steps=50,
            greater_is_better=True,
            report_to="none",
            seed=seed+fold,
            fp16=use_fp16 and not use_bf16,
            bf16=use_bf16,
            lr_scheduler_type="cosine",
            warmup_ratio=0.1,
            max_grad_norm=1.0,
            optim="adamw_torch",
        )

        data_collator = default_data_collator 
        trainer = WeightedTrainer(
            class_weight=class_weight,
            rdrop_alpha=1.0,
            layerwise_lr_decay=0.9,
            label_smoothing_factor=0.05,
            model=model,
            gamma=0.0,
            args=args,
            train_dataset=ds_tr,
            eval_dataset=ds_va,
            processing_class=tokenizer,
            data_collator=data_collator,
            compute_metrics=compute_f1,
            callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
        )

        resume_ckpt = None
        if os.path.isdir(output_dir):
            ckpts = glob.glob(os.path.join(output_dir, "checkpoint-*"))
            if ckpts:
                ckpts_sorted = sorted(ckpts, key=lambda p: int(p.split("-")[-1]))
                resume_ckpt = ckpts_sorted[-1]

        if resume_ckpt is not None:
            print("Resuming from checkpoint:", resume_ckpt)
            trainer.train(resume_from_checkpoint=resume_ckpt)
        else:
            print("No checkpoint found, training from scratch.")
            trainer.train()

        valid_logits = trainer.predict(ds_va).predictions
        oof_preds[va_idx] = valid_logits

        test_logits = trainer.predict(ds_te).predictions
        test_logits_accum += test_logits / n_splits

        va_pred = np.argmax(valid_logits, axis=1)
        f1 = f1_score(va_labels, va_pred, average="macro")
        print(f"Fold {fold} F1(macro): {f1:.4f}")

        del trainer, model
        torch.cuda.empty_cache()

    oof_pred_labels = oof_preds.argmax(axis=1)
    oof_f1_macro = f1_score(y, oof_pred_labels, average="macro")
    oof_f1_micro = f1_score(y, oof_pred_labels, average="micro")
    print(f"\n[Model {model_name}] OOF F1(macro): {oof_f1_macro:.4f} | micro: {oof_f1_micro:.4f}")

    return oof_preds, test_logits_accum

In [ ]:
torch.cuda.empty_cache()


SEEDS = [42, 2025] 

backbones = [
    # "GroNLP/hateBERT",
    # "microsoft/deberta-v3-large",
    # "FacebookAI/roberta-large",
    # "j-hartmann/emotion-english-roberta-large",
    "Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta",
    "cardiffnlp/twitter-roberta-large-emotion-latest",
]
cfgs = {
    "j-hartmann/emotion-english-roberta-large": dict(lr=1.5e-5, epochs=4),
    "FacebookAI/roberta-large": dict(lr=1.5e-5, epochs=4),
    "microsoft/deberta-v3-large": dict(lr=8e-6, epochs=4),
    "Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta": dict(lr=1.5e-5, epochs=4),
    "GroNLP/hateBERT": dict(lr=1.5e-5, epochs=4),
    "cardiffnlp/twitter-roberta-large-emotion-latest": dict(lr=1.5e-5, epochs=4),
}

all_oof, all_test = [], []

for name in backbones:
    hp = cfgs[name]
    for s in SEEDS:
        print(f"\n==== {name} | SEED {s} ====")
        oof, test_logits = train_folds(
            name,
            n_splits=5,
            lr=hp["lr"],
            epochs=hp["epochs"],
            bsz=16,
            max_len=128,
            wd=0.01,
            seed=s,
        )
        all_oof.append(oof)
        all_test.append(test_logits)



==== j-hartmann/emotion-english-roberta-large | SEED 42 ====


tokenizer_config.json:   0%|          | 0.00/328 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Adding 3 special tokens: ['<USER>', '<URL>', '<NAME>']

[j-hartmann/emotion-english-roberta-large] Fold 1/5


Map:   0%|          | 0/40088 [00:00<?, ? examples/s]

Map:   0%|          | 0/10023 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at j-hartmann/emotion-english-roberta-large and are newly initialized because the shapes did not match:
- classifier.out_proj.weight: found shape torch.Size([7, 1024]) in the checkpoint and torch.Size([6, 1024]) in the model instantiated
- classifier.out_proj.bias: found shape torch.Size([7]) in the checkpoint and torch.Size([6]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

No checkpoint found, training from scratch.


Fold 1 F1(macro): 0.5427

[j-hartmann/emotion-english-roberta-large] Fold 2/5


Map:   0%|          | 0/40089 [00:00<?, ? examples/s]

Map:   0%|          | 0/10022 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at j-hartmann/emotion-english-roberta-large and are newly initialized because the shapes did not match:
- classifier.out_proj.weight: found shape torch.Size([7, 1024]) in the checkpoint and torch.Size([6, 1024]) in the model instantiated
- classifier.out_proj.bias: found shape torch.Size([7]) in the checkpoint and torch.Size([6]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


No checkpoint found, training from scratch.


Fold 2 F1(macro): 0.5485

[j-hartmann/emotion-english-roberta-large] Fold 3/5


Map:   0%|          | 0/40089 [00:00<?, ? examples/s]

Map:   0%|          | 0/10022 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at j-hartmann/emotion-english-roberta-large and are newly initialized because the shapes did not match:
- classifier.out_proj.weight: found shape torch.Size([7, 1024]) in the checkpoint and torch.Size([6, 1024]) in the model instantiated
- classifier.out_proj.bias: found shape torch.Size([7]) in the checkpoint and torch.Size([6]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


No checkpoint found, training from scratch.


Fold 3 F1(macro): 0.5457

[j-hartmann/emotion-english-roberta-large] Fold 4/5


Map:   0%|          | 0/40089 [00:00<?, ? examples/s]

Map:   0%|          | 0/10022 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at j-hartmann/emotion-english-roberta-large and are newly initialized because the shapes did not match:
- classifier.out_proj.weight: found shape torch.Size([7, 1024]) in the checkpoint and torch.Size([6, 1024]) in the model instantiated
- classifier.out_proj.bias: found shape torch.Size([7]) in the checkpoint and torch.Size([6]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


No checkpoint found, training from scratch.


Fold 4 F1(macro): 0.5353

[j-hartmann/emotion-english-roberta-large] Fold 5/5


Map:   0%|          | 0/40089 [00:00<?, ? examples/s]

Map:   0%|          | 0/10022 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at j-hartmann/emotion-english-roberta-large and are newly initialized because the shapes did not match:
- classifier.out_proj.weight: found shape torch.Size([7, 1024]) in the checkpoint and torch.Size([6, 1024]) in the model instantiated
- classifier.out_proj.bias: found shape torch.Size([7]) in the checkpoint and torch.Size([6]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


No checkpoint found, training from scratch.


Fold 5 F1(macro): 0.5404

[Model j-hartmann/emotion-english-roberta-large] OOF F1(macro): 0.5425 | micro: 0.6855

==== Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta | SEED 42 ====
Adding 3 special tokens: ['<USER>', '<URL>', '<NAME>']

[Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta] Fold 1/5


Map:   0%|          | 0/40088 [00:00<?, ? examples/s]

Map:   0%|          | 0/10023 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta and are newly initialized because the shapes did not match:
- classifier.out_proj.bias: found shape torch.Size([28]) in the checkpoint and torch.Size([6]) in the model instantiated
- classifier.out_proj.weight: found shape torch.Size([28, 768]) in the checkpoint and torch.Size([6, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_multi-label-emotion-classification-reddit-comments-roberta_f1/checkpoint-6684


Fold 1 F1(macro): 0.6132

[Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta] Fold 2/5


Map:   0%|          | 0/40089 [00:00<?, ? examples/s]

Map:   0%|          | 0/10022 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta and are newly initialized because the shapes did not match:
- classifier.out_proj.bias: found shape torch.Size([28]) in the checkpoint and torch.Size([6]) in the model instantiated
- classifier.out_proj.weight: found shape torch.Size([28, 768]) in the checkpoint and torch.Size([6, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_multi-label-emotion-classification-reddit-comments-roberta_f2/checkpoint-5013


Fold 2 F1(macro): 0.6081

[Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta] Fold 3/5


Map:   0%|          | 0/40089 [00:00<?, ? examples/s]

Map:   0%|          | 0/10022 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta and are newly initialized because the shapes did not match:
- classifier.out_proj.bias: found shape torch.Size([28]) in the checkpoint and torch.Size([6]) in the model instantiated
- classifier.out_proj.weight: found shape torch.Size([28, 768]) in the checkpoint and torch.Size([6, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_multi-label-emotion-classification-reddit-comments-roberta_f3/checkpoint-6684


Fold 3 F1(macro): 0.6061

[Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta] Fold 4/5


Map:   0%|          | 0/40089 [00:00<?, ? examples/s]

Map:   0%|          | 0/10022 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta and are newly initialized because the shapes did not match:
- classifier.out_proj.bias: found shape torch.Size([28]) in the checkpoint and torch.Size([6]) in the model instantiated
- classifier.out_proj.weight: found shape torch.Size([28, 768]) in the checkpoint and torch.Size([6, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_multi-label-emotion-classification-reddit-comments-roberta_f4/checkpoint-6684


Fold 4 F1(macro): 0.5992

[Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta] Fold 5/5


Map:   0%|          | 0/40089 [00:00<?, ? examples/s]

Map:   0%|          | 0/10022 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta and are newly initialized because the shapes did not match:
- classifier.out_proj.bias: found shape torch.Size([28]) in the checkpoint and torch.Size([6]) in the model instantiated
- classifier.out_proj.weight: found shape torch.Size([28, 768]) in the checkpoint and torch.Size([6, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_multi-label-emotion-classification-reddit-comments-roberta_f5/checkpoint-5013


Fold 5 F1(macro): 0.6108

[Model Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta] OOF F1(macro): 0.6077 | micro: 0.7340


In [39]:
def optimized_ensemble(all_oof, all_test, y):
    X_oof = np.hstack(all_oof)
    
    meta_model = LogisticRegression(
        multi_class='multinomial',
        max_iter=1000,
        C=0.1,
        random_state=SEED
    )
    meta_model.fit(X_oof, y)
    
    oof_pred = meta_model.predict(X_oof)
    oof_f1 = f1_score(y, oof_pred, average="macro")
    print(f"\n[Stacked Ensemble] OOF F1(macro): {oof_f1:.4f}")
    
    X_test = np.hstack(all_test)
    test_proba = meta_model.predict_proba(X_test)
    
    return test_proba, oof_pred

test_proba, oof_pred = optimized_ensemble(all_oof, all_test, y)

oof_blend = np.mean(all_oof, axis=0)
test_blend = np.mean(all_test, axis=0)

oof_pred_avg = oof_blend.argmax(axis=1)
oof_f1_avg = f1_score(y, oof_pred_avg, average="macro")
print(f"[Simple Average] OOF F1(macro): {oof_f1_avg:.4f}")

if f1_score(y, oof_pred, average="macro") > oof_f1_avg:
    print("Using stacked ensemble")
    final_predictions = test_proba.argmax(axis=1)
else:
    print("Using simple average")
    final_predictions = test_blend.argmax(axis=1)

oof_pred = oof_blend.argmax(axis=1)
print(classification_report(y, oof_pred, target_names=labels))

cm = confusion_matrix(y, oof_pred)
print(cm)

/venv/main/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(



[Stacked Ensemble] OOF F1(macro): 0.6029
[Simple Average] OOF F1(macro): 0.5876
Using stacked ensemble
              precision    recall  f1-score   support

       anger       0.65      0.65      0.65     10694
     disgust       0.30      0.33      0.31      1183
        fear       0.47      0.74      0.58      2009
         joy       0.87      0.82      0.84     26018
     sadness       0.50      0.54      0.52      3926
    surprise       0.61      0.62      0.62      6281

    accuracy                           0.72     50111
   macro avg       0.57      0.62      0.59     50111
weighted avg       0.73      0.72      0.73     50111

[[ 6937   453   491  1303   749   761]
 [  354   396   129   117   141    46]
 [  129    68  1490   129   121    72]
 [ 1814   211   584 21205   808  1396]
 [  693   134   253   482  2137   227]
 [  704    73   193  1102   293  3916]]


In [40]:
test_labels = [id2label[i] for i in final_predictions]
submission = pd.DataFrame({"id": test_df["id"].values, "emotion": test_labels})
sub_path = "./submit/submission.csv"
os.makedirs("./submit", exist_ok=True)
submission.to_csv(sub_path, index=False)
print("Saved:", sub_path)
submission.head()

Saved: ./submit/submission.csv


id emotion
0  0x61fc95     joy
1  0xaba820    fear
2  0x66e44d     joy
3  0xc03cf5     joy
4  0x02f65a   anger

In [41]:
probs = test_proba 
preds = probs.argmax(axis=1)
confidences = probs.max(axis=1)

mask = confidences > 0.95
pseudo_df = test_df[mask].copy()
pseudo_df["emotion"] = [id2label[p] for p in preds[mask]]
pseudo_df["split"] = "train" 

print(f"Original Train Size: {len(train_df)}")
print(f"Adding {len(pseudo_df)} pseudo-labels (Confidence > 0.95)")

train_df = pd.concat([train_df, pseudo_df], ignore_index=True)
y = train_df["emotion"].map(label2id).values.astype(int)

print(f"New Train Size: {len(train_df)}")

pseudo_all_test_logits = []
pseudo_all_oof = []


for name in backbones:
    hp = cfgs.get(name, {"lr": 1e-5, "epochs": 3}) 
    
    safe_lr = hp["lr"] * 0.6 
    
    print(f"\n[Pseudo-Label Retrain] Model: {name}")
    
    oof, test_logits = train_folds(
        name,
        n_splits=5,
        lr=safe_lr,     
        epochs=hp["epochs"],
        bsz=16,          
        max_len=128
    )
    pseudo_all_test_logits.append(test_logits)
    pseudo_all_oof.append(oof)

final_ensemble_logits = np.mean(pseudo_all_test_logits, axis=0)
final_preds = final_ensemble_logits.argmax(axis=1)
final_labels = [id2label[i] for i in final_preds]

sub_path = "./submit/submission_pseudo.csv"
submission = pd.DataFrame({"id": test_df["id"].values, "emotion": final_labels})
submission.to_csv(sub_path, index=False)
print(f"Saved Full Ensemble Pseudo Submission: {sub_path}")

Original Train Size: 50111
Adding 2626 pseudo-labels (Confidence > 0.95)
New Train Size: 52737

[Pseudo-Label Retrain] Model: j-hartmann/emotion-english-roberta-large


Adding 3 special tokens: ['<USER>', '<URL>', '<NAME>']

[j-hartmann/emotion-english-roberta-large] Fold 1/5


Map:   0%|          | 0/42189 [00:00<?, ? examples/s]

Map:   0%|          | 0/10548 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at j-hartmann/emotion-english-roberta-large and are newly initialized because the shapes did not match:
- classifier.out_proj.weight: found shape torch.Size([7, 1024]) in the checkpoint and torch.Size([6, 1024]) in the model instantiated
- classifier.out_proj.bias: found shape torch.Size([7]) in the checkpoint and torch.Size([6]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_emotion-english-roberta-large_f1/checkpoint-5013


Fold 1 F1(macro): 0.5704

[j-hartmann/emotion-english-roberta-large] Fold 2/5


Map:   0%|          | 0/42189 [00:00<?, ? examples/s]

Map:   0%|          | 0/10548 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at j-hartmann/emotion-english-roberta-large and are newly initialized because the shapes did not match:
- classifier.out_proj.weight: found shape torch.Size([7, 1024]) in the checkpoint and torch.Size([6, 1024]) in the model instantiated
- classifier.out_proj.bias: found shape torch.Size([7]) in the checkpoint and torch.Size([6]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_emotion-english-roberta-large_f2/checkpoint-3342


Fold 2 F1(macro): 0.5761

[j-hartmann/emotion-english-roberta-large] Fold 3/5


Map:   0%|          | 0/42190 [00:00<?, ? examples/s]

Map:   0%|          | 0/10547 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at j-hartmann/emotion-english-roberta-large and are newly initialized because the shapes did not match:
- classifier.out_proj.weight: found shape torch.Size([7, 1024]) in the checkpoint and torch.Size([6, 1024]) in the model instantiated
- classifier.out_proj.bias: found shape torch.Size([7]) in the checkpoint and torch.Size([6]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_emotion-english-roberta-large_f3/checkpoint-5013


Fold 3 F1(macro): 0.5831

[j-hartmann/emotion-english-roberta-large] Fold 4/5


Map:   0%|          | 0/42190 [00:00<?, ? examples/s]

Map:   0%|          | 0/10547 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at j-hartmann/emotion-english-roberta-large and are newly initialized because the shapes did not match:
- classifier.out_proj.weight: found shape torch.Size([7, 1024]) in the checkpoint and torch.Size([6, 1024]) in the model instantiated
- classifier.out_proj.bias: found shape torch.Size([7]) in the checkpoint and torch.Size([6]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_emotion-english-roberta-large_f4/checkpoint-6684


Fold 4 F1(macro): 0.5890

[j-hartmann/emotion-english-roberta-large] Fold 5/5


Map:   0%|          | 0/42190 [00:00<?, ? examples/s]

Map:   0%|          | 0/10547 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at j-hartmann/emotion-english-roberta-large and are newly initialized because the shapes did not match:
- classifier.out_proj.weight: found shape torch.Size([7, 1024]) in the checkpoint and torch.Size([6, 1024]) in the model instantiated
- classifier.out_proj.bias: found shape torch.Size([7]) in the checkpoint and torch.Size([6]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_emotion-english-roberta-large_f5/checkpoint-5013


Fold 5 F1(macro): 0.5617

[Model j-hartmann/emotion-english-roberta-large] OOF F1(macro): 0.5759 | micro: 0.7210

[Pseudo-Label Retrain] Model: Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta
Adding 3 special tokens: ['<USER>', '<URL>', '<NAME>']

[Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta] Fold 1/5


Map:   0%|          | 0/42189 [00:00<?, ? examples/s]

Map:   0%|          | 0/10548 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta and are newly initialized because the shapes did not match:
- classifier.out_proj.bias: found shape torch.Size([28]) in the checkpoint and torch.Size([6]) in the model instantiated
- classifier.out_proj.weight: found shape torch.Size([28, 768]) in the checkpoint and torch.Size([6, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_multi-label-emotion-classification-reddit-comments-roberta_f1/checkpoint-6684


Fold 1 F1(macro): 0.6036

[Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta] Fold 2/5


Map:   0%|          | 0/42189 [00:00<?, ? examples/s]

Map:   0%|          | 0/10548 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta and are newly initialized because the shapes did not match:
- classifier.out_proj.bias: found shape torch.Size([28]) in the checkpoint and torch.Size([6]) in the model instantiated
- classifier.out_proj.weight: found shape torch.Size([28, 768]) in the checkpoint and torch.Size([6, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_multi-label-emotion-classification-reddit-comments-roberta_f2/checkpoint-5013


Fold 2 F1(macro): 0.6043

[Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta] Fold 3/5


Map:   0%|          | 0/42190 [00:00<?, ? examples/s]

Map:   0%|          | 0/10547 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta and are newly initialized because the shapes did not match:
- classifier.out_proj.bias: found shape torch.Size([28]) in the checkpoint and torch.Size([6]) in the model instantiated
- classifier.out_proj.weight: found shape torch.Size([28, 768]) in the checkpoint and torch.Size([6, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_multi-label-emotion-classification-reddit-comments-roberta_f3/checkpoint-6684


Fold 3 F1(macro): 0.6141

[Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta] Fold 4/5


Map:   0%|          | 0/42190 [00:00<?, ? examples/s]

Map:   0%|          | 0/10547 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta and are newly initialized because the shapes did not match:
- classifier.out_proj.bias: found shape torch.Size([28]) in the checkpoint and torch.Size([6]) in the model instantiated
- classifier.out_proj.weight: found shape torch.Size([28, 768]) in the checkpoint and torch.Size([6, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_multi-label-emotion-classification-reddit-comments-roberta_f4/checkpoint-6684


Fold 4 F1(macro): 0.6224

[Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta] Fold 5/5


Map:   0%|          | 0/42190 [00:00<?, ? examples/s]

Map:   0%|          | 0/10547 [00:00<?, ? examples/s]

Map:   0%|          | 0/16281 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta and are newly initialized because the shapes did not match:
- classifier.out_proj.bias: found shape torch.Size([28]) in the checkpoint and torch.Size([6]) in the model instantiated
- classifier.out_proj.weight: found shape torch.Size([28, 768]) in the checkpoint and torch.Size([6, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Resuming from checkpoint: ./out_multi-label-emotion-classification-reddit-comments-roberta_f5/checkpoint-5013


Fold 5 F1(macro): 0.5987

[Model Amirhossein75/multi-label-emotion-classification-reddit-comments-roberta] OOF F1(macro): 0.6085 | micro: 0.7467
Saved Full Ensemble Pseudo Submission: ./submit/submission_pseudo.csv


In [42]:
n_pseudo = len(pseudo_df)
n_total = len(y) 
n_original = n_total - n_pseudo

print(f"Total Samples: {n_total} | Original: {n_original} | Pseudo: {n_pseudo}")

y_real = y[:n_original]
oof_real = pseudo_all_oof[0][:n_original] 
pred_real = oof_real.argmax(axis=1)

cm = confusion_matrix(y_real, pred_real)
print("\nConfusion Matrix (Rows=True, Cols=Predicted):")
print(cm)

print("\nClassification Report (Original Data Only):")
print(classification_report(y_real, pred_real, target_names=labels))

Total Samples: 52737 | Original: 50111 | Pseudo: 2626

Confusion Matrix (Rows=True, Cols=Predicted):
[[ 6838   532   532  1283   722   787]
 [  356   415   126   100   143    43]
 [  131    69  1479   138   119    73]
 [ 1939   260   642 20825   861  1491]
 [  759   157   268   472  2010   260]
 [  745    85   199  1114   293  3845]]

Classification Report (Original Data Only):
              precision    recall  f1-score   support

       anger       0.64      0.64      0.64     10694
     disgust       0.27      0.35      0.31      1183
        fear       0.46      0.74      0.56      2009
         joy       0.87      0.80      0.83     26018
     sadness       0.48      0.51      0.50      3926
    surprise       0.59      0.61      0.60      6281

    accuracy                           0.71     50111
   macro avg       0.55      0.61      0.57     50111
weighted avg       0.72      0.71      0.71     50111

